"""Export all shared schemas for easy consumption."""

from shared.schemas.application import (
    ApplicationBase,
    ApplicationCreate,
    ApplicationFilter,
    ApplicationResponse,
    ApplicationStatus,
    ApplicationStatusUpdate,
    ApplicationUpdate,
    TimelineEntry,
)
from shared.schemas.interview_lab import (
    ExperienceBase,
    ExperienceCreate,
    ExperienceResponse,
    ExperienceUpdate,
    FlashCardBase,
    FlashCardCreate,
    FlashCardResponse,
    FlashCardUpdate,
    InterviewProcessStep,
    InterviewQA,
    QuestionBase,
    QuestionCreate,
    QuestionResponse,
    QuestionUpdate,
    ResourceLink,
    SolutionEntry,
    TagBase,
    TagCreate,
    TagResponse,
    TagUpdate,
)
from shared.schemas.prep import (
    PrepDocCreate,
    PrepDocResponse,
    QuestionCategory,
    SourcedItem,
)
from shared.schemas.profile import (
    EligibilityProfile,
    SeniorityLevel,
)
from shared.schemas.resume import (
    ResumeBullet,
    ResumeSection,
    ResumeVersionCreate,
    ResumeVersionResponse,
    StructuredResume,
)

__all__ = [
    "ApplicationBase",
    "ApplicationCreate",
    "ApplicationFilter",
    "ApplicationResponse",
    "ApplicationStatus",
    "ApplicationStatusUpdate",
    "ApplicationUpdate",
    "EligibilityProfile",
    "ExperienceBase",
    "ExperienceCreate",
    "ExperienceResponse",
    "ExperienceUpdate",
    "FlashCardBase",
    "FlashCardCreate",
    "FlashCardResponse",
    "FlashCardUpdate",
    "InterviewProcessStep",
    "InterviewQA",
    "PrepDocCreate",
    "PrepDocResponse",
    "QuestionBase",
    "QuestionCategory",
    "QuestionCreate",
    "QuestionResponse",
    "QuestionUpdate",
    "ResourceLink",
    "ResumeBullet",
    "ResumeSection",
    "ResumeVersionCreate",
    "ResumeVersionResponse",
    "SeniorityLevel",
    "SolutionEntry",
    "SourcedItem",
    "StructuredResume",
    "TagBase",
    "TagCreate",
    "TagResponse",
    "TagUpdate",
    "TimelineEntry",
]
